test/test_add_grouppp.py:None (test/test_add_grouppp.py)
env\lib\site-packages\pluggy\_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
env\lib\site-packages\pluggy\_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
env\lib\site-packages\_pytest\python.py:257: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
env\lib\site-packages\_pytest\python.py:480: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
env\lib\site-packages\pluggy\_hooks.py:292: in call_extra
    return self(**kwargs)
env\lib\site-packages\pluggy\_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
env\lib\site-packages\pluggy\_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
conftest.py:70: in pytest_generate_tests
    metafunc.parametrize(fixture, testdata, ids=[str(x) for x in testdata])
E   TypeError: 'NoneType' object is not iterable


Assertion failed